# Generated by Django 5.2.7 on 2025-10-15 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_authors_book_authors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authors',
            new_name='Author',
        ),
    ]
